import 'package:cloud_firestore/cloud_firestore.dart';

class ClassVideo {
  final String id; // Firestore doc id
  final String filename;
  final String publicId;
  final String url;
  final String sectionTitle;
  final int sectionOrder;
  final int uploadedAt;

  ClassVideo({
    required this.id,
    required this.filename,
    required this.publicId,
    required this.url,
    required this.sectionTitle,
    required this.sectionOrder,
    required this.uploadedAt,
  });

  factory ClassVideo.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return ClassVideo(
      id: doc.id,
      filename: data['filename'] as String,
      publicId: data['publicId'] as String,
      url: data['url'] as String,
      sectionTitle: data['sectionTitle'] as String,
      sectionOrder: data['sectionOrder'] as int,
      uploadedAt: data['uploadedAt'] as int,
    );
  }

  /// back-compat name used in some UIs
  String get docId => id;

  /// thumbnail URL generated by Cloudinary (replace cloud name)
  /// Example transformation: width 300, height 200, fill crop
  String get thumbnailUrl =>
      'https://res.cloudinary.com/<your-cloud-name>/video/upload/w_300,h_200,c_fill/$publicId.jpg';

  /// HLS (.m3u8) stream url (Cloudinary exposes HLS variants by adding .m3u8)
  String get hlsUrl {
    // if url already ends with .m3u8 just return
    if (url.endsWith('.m3u8')) return url;
    // typical Cloudinary returns .mp4 in secureUrl; convert to .m3u8
    return url.replaceAll(RegExp(r'\.\w+$'), '.m3u8');
  }
}
